apiVersion: v1
kind: Service
metadata:
 name: flask-app
spec:
 type: ClusterIP
 selector:
  app: task2-app
 ports:
  - protocol: TCP
    port: 5000

---

apiVersion: v1
kind: Pod
metadata: 
 name: task2-app
 labels:
  app: task2-app
spec:
  containers:
  - name: task2-app
    imagePullPolicy: Always
    image: satishgssk/task2-app
    ports: 
     - containerPort: 5000
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Password123