apiVersion: v1
kind: Service
metadata:
 name: mysql
spec:
 type: ClusterIP
 selector:
  app: task2-db
 ports:
  - port: 3306
    targetPort: 3306

---

apiVersion: v1
kind: Pod
metadata: 
 name: task2-db
 labels:
  app: task2-db
spec:
  containers:
  - name: task2-db
    imagePullPolicy: Always
    image: satishgssk/task2-db
    ports: 
     - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom: 
        secretKeyRef:
          name: db-root-password
          key: password
